- hosts: kubernetes
  tasks:
    - name: crear nuevo deployment
      command: kubectl apply -f /home/alumno/Deployment.yml
    - name: crear nuevo service
      command: kubectl apply -f /home/alumno/Service.yml
