- hosts: kubernetes
  tasks:
    - name: borrar antiguo centos
      command: kubectl delete -f /home/alumno/centos.yml
      failed_when: false

    - name: borrar antiguo mongodb
      command: kubectl delete -f /home/alumno/mongodb.yml
      failed_when: false

    - name: borrar antiguo prometheus
      command: helm uninstall prometheus
      failed_when: false

    - name: borrar antiguo mongodb-exporter
      command: helm uninstall mongodb-exporter
      failed_when: false

    - name: crear nuevo centos
      command: kubectl apply -f /home/alumno/centos.yml

    - name: crear nuevo mongodb
      command: kubectl apply -f /home/alumno/mongodb.yml

    - name: instalar prometheus
      command:
        cmd: "{{ item }}"
      loop:
        - helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        - helm repo update
        - helm install prometheus prometheus-community/kube-prometheus-stack

    - name: instalar mongodb-exporter para prometheus
      command: helm install mongodb-exporter prometheus-community/prometheus-mongodb-exporter --version=2.8.1 -f mongodb-exporter.yml

    - name: Crear archivo
      file:
        path: /home/alumno/LEEME.txt
        state: touch
        backup: "yes"

    - name: Agregar línea al archivo
      lineinfile:
        path: /home/alumno/LEEME.txt
        line: "Monitorización Prometheus: kubectl port-forward prometheus-prometheus-kube-prometheus-prometheus-0 9090"
        create: yes

    - name: Agregar línea al archivo
      lineinfile:
        path: /home/alumno/LEEME.txt
        line: "Monitorización Grafana: kubectl port-forward deployment/prometheus-grafana 3000"
        create: yes
#
