- hosts: kubernetes
  tasks:
    - name: iniciar minikube
      command: minikube start
    - name: borrar antiguo centos
      command: kubectl delete -f /home/alumno/centos.yml
    - name: borrar antiguo mongodb
      command: kubectl delete -f /home/alumno/mongodb.yml
    - name: crear nuevo centos
      command: kubectl apply -f /home/alumno/centos.yml
    - name: crear nuevo mongodb
      command: kubectl apply -f /home/alumno/mongodb.yml
