- hosts: all
  connection: local
  become: true
  tasks:
    - name: create new deployment
      shell: "kubectl apply -f . --kubeconfig=/home/alumno/.kube/config"
    - name: create new service
      shell: kubectl apply -f /home/alumno/Service.yml
