- hosts: all
  connection: local
  become: yes
  tasks:
    - name: create new deployment
      command: kubectl apply -f /home/alumno/Deployment.yml
    - name: create new service
      command: kubectl apply -f /home/alumno/Service.yml
