- hosts: all
  connection: local
  become: true
  tasks:
    - name: create new deployment
      command: kubectl apply -f . --kubeconfig=/home/alumno/.kube/config"
    - name: create new service
      raw: kubectl apply -f /home/alumno/Service.yml
