kind: Deployment
apiVersion: apps/v1
metadata:
  name: centosDeployment #Nombre del deployemnt/pod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: centosDeployment #Le decimos que el mismo pertenece a este deployment
  template:
    metadata:
      labels:
        app: centosDeployment
    spec:
      containers:
        - name: centosjenkins #Indico un nombre significativo de que contiene esta imagen
          image: joseangelgarciagarcia/kubernetes-pipeline #DOCKERHUB
          imagePullPolicy: Always
          ports:
            - containerPort: 80 #Puerto interno del pod
---
kind: Service
apiVersion: v1
metadata:
  name: centosService #Nombre del service/contenedor
  labels:
    app: centosService
spec:
  ports:
    - port: 8080 #Puerto expuesto del contenedor, para acceder desde internet
      targetPort: 80 #Puerto interno del pod
      nodePort: 31200 #Para acceder a el si estamos dentro del clúster desde cualquier nodo
  selector:
    app: centosDeployment #A que pod/Deployment pertenece
  type: LoadBalancer #Para que nuestro servicio pueda ser visto fuera del cluster
